cloud:
  aws:
    credentials:
      access-key-id: ASIAZ7ZFBDOWLWZO5FEJ
      secret-access-key: 3c2flgVOsFD8k+80YbyLmgskUJNjY9gYwVVxq+YA
      session-token: FwoGZXIvYXdzEBIaDIjzcoPt/oVdbbZOJCLAAeQWUPP9tLD7UO+FXiihOQcMMm9KGN4xnBe2RzeJ2Z1WAwFxyLgkPgvz/kgrwaz/OtdKav2tWipayi0bhBoIO1lfwnsOXthc0jNvkkjldigwSqQXCt7nsIDv9qk6wO5jRmhS08aOPNQRY/7YJOLc+uRy5VIYrETVVEkm9yDRkMA/NN9xuWJvDKsof03SUQQSDCsVkz/jNOC5m93azTcLEOxlcn/z+3iVLZ8khnczREIM4o/3wvUDx0Nm/Aglm8zRJiibxrOSBjItwqsEu+SgqBaYrR/Uas8A0bowPpIEj/n2PsSFidgDd0PWeqvBM6zYWOYWIYre
    region:
      static: us-east-1
      auto: false
