cloud:
  aws:
    credentials:
      access-key-id: ASIAZ7ZFBDOWHHOJUAWU
      secret-access-key: 1DiclSJBL9ZL/siqIYhfodnnCntP9AHrSDcIFah+
      session-token: FwoGZXIvYXdzEBYaDOP0PEbGf1ZR0sCR6CLAAXEXRMi6bk8jALB1ohG8gNA2ddLNRTo5zBvhAdphA9+P13ZgdQlq+dhHeJ+1jPTsG0MwdZm5dOxT+tT6ILxGCDbZUR7mCUnt1ut+m5cZjPYexFoy7Q/xNzcuFyvqLmiJJSremaRMMbjINVy9jZgdJDAFQ4aMUFydUXi3sR+UScIjmzctgSAUDuWgqo9gHFYAdJpSp+wk1kqoj1rpbgYIpsSVyd1JNeZFUcOSsSSEMaodqhx4bMB6KAjzkrkRH7ENDijrt7SSBjItj44VmkV1FSrEVNMD94MO5jaoySWohDv5SC8VaPf7RCOm5q7fo7KR+L8d9DoF
    region:
      static: us-east-1
      auto: false
