cloud:
  aws:
    credentials:
      access-key-id: ASIAZ7ZFBDOWFH3DYSOE
      secret-access-key: achkPy/B7L3hq43MlK/AnUePlu/5RhYWxl1Tktmy
      session-token: FwoGZXIvYXdzECUaDFKuxFyJG32EdFnzCyLAAZUTEikLueOwNLTR21Y5F6onFvp9LXCCoABZ0yszUdqp82AYGmu1kKmew2FasxH4IJ0uOON1Az7JHL6y0Ne2htrUDvsnRz5wWG5J6Jg86495a8uGArMWUCTvO+DfcjUClYB10iNdgkqFnyFgJyp+nRmFR+y3CsINcQ9t8/2h0f19n/bd5IN1GfwXOjzHt3w6/HwYkDOeYkPojRuYh0W36+lJ8/EKi80ridcZ4wnZ9Wf00n2O6MAMbvA30rJeF/UHeyjR0beSBjItHPRzUD9t/mT4bIxswO+1t3UFBHzxV9wnHLVzDmfC95PeVn+WDQTocKz9s/cF
    region:
      static: us-east-1
      auto: false
