cloud:
  aws:
    credentials:
      access-key-id: ASIAZ7ZFBDOWI3DVN5HN
      secret-access-key: kph+V03GtJQ6aYTpC0SrQmOSlNicRKszVUQIjcOK
      session-token: FwoGZXIvYXdzEAsaDA8GybLXeK+BSVNExyLAASqXiv04bILu96CcrXnY3UIJ/Raj/e02b3ma+Wh2J4UplcxBLcy2zVbZnu+iLGXXMqDP/aAAFFvHoRTMmjVL0m8IVdM8EU0DNTkyFvTPqhXGK4M91Cti+hjp1CdsDMQaBxzlWEmqlviJgjcH0LMS5u5WwadLfzvelO70NF5+yfYGN+ocLY+DmbMmxrMTjnEgyx+6nTJQMyjaatw5/qSRV1E6aoTsjyn7oZF9EQf+i/WaHtsErvytxyTIURWmQmLw5ijD8rGSBjItObTD0qI/+yNU6fxyjf+vmhSffyePiUbDecoV18TOkYQ0HMdZ+6L80j247NWd
    region:
      static: us-east-1
      auto: false